services:
  app:
    image: civicrm/civicrm:latest
    restart: unless-stopped
    ports:
      - 8760:80
    volumes:
      - ./private:/var/www/html/private
      - ./public:/var/www/html/public
      - ./ext:/var/www/html/ext
    environment:
      CIVICRM_DB_HOST: mariadb
      CIVICRM_DB_PORT: 3306
      CIVICRM_DB_NAME: civicrm
      CIVICRM_DB_USER: civicrm
      CIVICRM_DB_PASSWORD: civicrm
      CIVICRM_DB_ROOT_PASSWORD: civicrm
      CIVICRM_UF_BASEURL: "http://localhost:8760/"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: civicrm
      MYSQL_DATABASE: civicrm
      MYSQL_USER: civicrm
      MYSQL_PASSWORD: civicrm
    volumes:
      - ./db:/var/lib/mysql
    command: 
      - --max-allowed-packet=256M
      - --innodb-log-file-size=100M
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 20