#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

# Recursively set ownership of all bind mounts to 1000:1000
# Also ensure proper permissions for Vikunja to write to these directories
mkdir -p "${APP_DATA_DIR}/data/config" "${APP_DATA_DIR}/data/db"
sudo chown -R 1000:1000 "${APP_DATA_DIR}"
chmod -R 755 "${APP_DATA_DIR}"