#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

# Recursively set ownership of all bind mounts to 1000:1000. wikijs was running as root for pre-2.5.306-1 installs
# even though it was using "correct" PUID/PGID env vars for linuxserver.io images.
chown -R 1000:1000 "${APP_DATA_DIR}"